### ISSUE TITLE
Hemme - Review

### ISSUE THREAD

**Issue by hayhem** [Anna9877/AnnabellaHines-MADA-project#3]
Hi Annabella,

Good job so far! I appreciate your detailed comments, which made it easy to follow along with what you're doing in your code! 

There were only a few issues I ran into: 
	1. I couldn't find where riskUS was called in your code. I'm not sure this was appropriate, but I used `risk` so that I could continue running the code. 
	2. line 218 -- the name of the object was wrong.
	3. Exploratory analysis has two files that appear to be the same- one is a Quarto file and the other is an Rmarkdown file. The file type is specified as '.rmarkdown' instead of '.Rmd', so I wasn't able to open this file until R Studio was opened.

Aside from that, my only suggestion would be to perhaps transform or check if your data predictors are either a rate or a percentage or proportion of the population. I'm not familiar with your data, but it seems like for the 'risk' part of your data, the data is in counts, which might make it difficult to compare across countries.  

Also, I just want to share this incase you aren't aware. 
life_data_location <- here::here("data","processed_data","processeddata_life.rds")

life <- readRDS(life_data_location)

I can imagine that in some instances that keeping these step separate might be useful, but it is possible to combine these steps. 

An example of how to do this for the code above would be:

life <- readRDS(here("data/processed_data/processeddata_life.rds")) 

I'm not super familiar with the method you used, but one thing that I find especially useful about the method I provided is that you're able to 'tab' using the tab key (this works on Windows, and I'd imagine Mac, but I don't know) through the folders and file, as opposed to typing them in.

Good luck with the next steps of your project! 
2/3

**Comment by Anna9877** [comment]
Thank you so much for your comments! These were super helpful and I've been having a difficult time with finding a good direction to take this project, but this definitely helps. Thank you again so much for the advice!
